import type { Product } from "@/types/product";

/**
 * LXS 3.0
 *
 * Copy is provisional and awaiting brand approval. Every specification, price,
 * colour, feature and warranty term below is `null` or empty until the
 * dealership supplies confirmed figures — see `_template.ts` for a fully
 * populated example, including how to express variant-level differences.
 */
export const lxs30: Product = {
  slug: "lxs-3-0",
  name: "LXS 3.0",
  tagline: "The everyday commuter, evolved.",
  description:
    "The newest generation of the LXS commuter platform, aimed at riders who cover a predictable city route every day and want the least fuss possible.",
  category: "commuter",
  order: 2,
  featured: true,

  // Baseline specification for the model. Variants override individual fields.
  specs: {
    batteryCapacityKwh: null,
    batteryRemovable: null,
    batteryChemistry: null,
    range: { claimedKm: null, realWorldKm: null },
    topSpeedKmph: null,
    accelerationSeconds: null,
    charging: { fullChargeHours: null, eightyPercentHours: null, chargerType: null },
    motor: { type: null, ratedPowerW: null, peakPowerW: null },
    gradeabilityPercent: null,
    ipRating: null,
    bootSpaceLitres: null,
    kerbWeightKg: null,
    ridingModes: [],
  },

  // Add one entry per variant the showroom actually sells. A variant lists
  // ONLY the specs that differ from the baseline above.
  variants: [
    {
      id: "standard",
      name: "Standard",
      price: null,
      availability: "available",
      specs: {},
      baas: null,
    },
  ],
  defaultVariantId: "standard",

  // Connected features offered through the Lectrix EV app.
  smartFeatures: [
    "mobile-app",
    "geo-fencing",
    "navigation",
    "anti-theft",
    "sos",
    "vehicle-monitoring",
  ],
  // Empty until the dealership confirms which features this model carries.
  // Ids must exist in src/data/feature-catalog.ts.
  safetyFeatures: [],
  comfortFeatures: [],

  colors: [],
  // Placeholder artwork generated by `scripts/generate-placeholder-images.py`.
  // Every file carries a visible PLACEHOLDER badge; swap in real photography
  // at the same paths and sizes and nothing else needs to change.
  images: {
    card: "/images/products/lxs-3-0-card.png",
    hero: "/images/products/lxs-3-0-hero.png",
    og: "/images/products/lxs-3-0-og.png",
  },
  gallery: [
    {
      src: "/images/products/lxs-3-0-gallery-1.png",
      alt: "Lectrix LXS 3.0 — three-quarter front (placeholder visual)",
      width: 1600,
      height: 1200,
    },
    {
      src: "/images/products/lxs-3-0-gallery-2.png",
      alt: "Lectrix LXS 3.0 — side profile (placeholder visual)",
      width: 1600,
      height: 1200,
    },
    {
      src: "/images/products/lxs-3-0-gallery-3.png",
      alt: "Lectrix LXS 3.0 — rear three-quarter (placeholder visual)",
      width: 1600,
      height: 1200,
    },
    {
      src: "/images/products/lxs-3-0-gallery-4.png",
      alt: "Lectrix LXS 3.0 — console detail (placeholder visual)",
      width: 1600,
      height: 1200,
    },
  ],
  warranty: { vehicle: null, battery: null, notes: null },

  faqs: [],
  dataStatus: {
    specsConfirmed: false,
    pricingConfirmed: false,
    featuresConfirmed: false,
    warrantyConfirmed: false,
    colorsConfirmed: false,
    imagesSupplied: false,
  },
};
