import type { Product } from "@/types/product";

/**
 * NDuro
 *
 * Copy is provisional and awaiting brand approval. Every specification, price,
 * colour, feature and warranty term below is `null` or empty until the
 * dealership supplies confirmed figures — see `_template.ts` for a fully
 * populated example, including how to express variant-level differences.
 */
export const nduro: Product = {
  slug: "nduro",
  name: "NDuro",
  tagline: "Built for the long way round.",
  description:
    "NDuro is the touring end of the Lectrix EV lineup — sized for riders who want a planted, comfortable scooter for longer daily runs rather than short hops.",
  category: "performance",
  order: 1,
  featured: true,

  // Baseline specification for the model. Variants override individual fields.
  specs: {
    batteryCapacityKwh: null,
    batteryRemovable: null,
    batteryChemistry: null,
    range: { claimedKm: null, realWorldKm: null },
    topSpeedKmph: null,
    accelerationSeconds: null,
    charging: { fullChargeHours: null, eightyPercentHours: null, chargerType: null },
    motor: { type: null, ratedPowerW: null, peakPowerW: null },
    gradeabilityPercent: null,
    ipRating: null,
    bootSpaceLitres: null,
    kerbWeightKg: null,
    ridingModes: [],
  },

  // Add one entry per variant the showroom actually sells. A variant lists
  // ONLY the specs that differ from the baseline above.
  variants: [
    {
      id: "standard",
      name: "Standard",
      price: null,
      availability: "available",
      specs: {},
      baas: null,
    },
  ],
  defaultVariantId: "standard",

  // Connected features offered through the Lectrix EV app.
  smartFeatures: [
    "mobile-app",
    "geo-fencing",
    "navigation",
    "anti-theft",
    "sos",
    "vehicle-monitoring",
  ],
  // Empty until the dealership confirms which features this model carries.
  // Ids must exist in src/data/feature-catalog.ts.
  safetyFeatures: [],
  comfortFeatures: [],

  colors: [],
  // Placeholder artwork generated by `scripts/generate-placeholder-images.py`.
  // Every file carries a visible PLACEHOLDER badge; swap in real photography
  // at the same paths and sizes and nothing else needs to change.
  images: {
    card: "/images/products/nduro-card.png",
    hero: "/images/products/nduro-hero.png",
    og: "/images/products/nduro-og.png",
  },
  gallery: [
    {
      src: "/images/products/nduro-gallery-1.png",
      alt: "Lectrix NDuro — three-quarter front (placeholder visual)",
      width: 1600,
      height: 1200,
    },
    {
      src: "/images/products/nduro-gallery-2.png",
      alt: "Lectrix NDuro — side profile (placeholder visual)",
      width: 1600,
      height: 1200,
    },
    {
      src: "/images/products/nduro-gallery-3.png",
      alt: "Lectrix NDuro — rear three-quarter (placeholder visual)",
      width: 1600,
      height: 1200,
    },
    {
      src: "/images/products/nduro-gallery-4.png",
      alt: "Lectrix NDuro — console detail (placeholder visual)",
      width: 1600,
      height: 1200,
    },
  ],
  warranty: { vehicle: null, battery: null, notes: null },

  faqs: [],
  dataStatus: {
    specsConfirmed: false,
    pricingConfirmed: false,
    featuresConfirmed: false,
    warrantyConfirmed: false,
    colorsConfirmed: false,
    imagesSupplied: false,
  },
};
